### ISSUE TITLE
Compiling launcher.ahk doesn't work

### ISSUE THREAD

**Issue by rollingmoai** [AutoHotkey/AutoHotkeyUX#2]
Hi, I have tried compiling https://github.com/AutoHotkey/AutoHotkeyUX/blob/main/launcher.ahk as specified in the file. It seems to compile just fine, but trying to run scripts doesn't seem to do anything. I have used this command to compile the script:
```powershell
.\Compiler\Ahk2Exe.exe /in .\UX\launcher.ahk /out .\UX\AutoHotkey.exe /base .\v2\AutoHotkey64.exe
```
Am I doing something wrong on my end? Thanks.

---
Also, the issues tab in https://github.com/AutoHotkey/AutoHotkey are closed. Is this intentional?

**Comment by Lexikos** [comment]
I haven't compiled the launcher recently. The `A_ScriptFullPath == A_LineFile` check only works if the script is uncompiled or is compiled with a .bin file as the base (which would now require building the .bin file yourself from source code, since they are no longer included in releases).

> Is this intentional?

Yes. I have considered using the issue tracker for tracking bugs and features, but having it enabled attracts posts that would be much more likely to get a helpful response in the Ask for Help forum.
