### ISSUE TITLE
There is no such thing as a "default script editor" in AutoHotkey

### ISSUE THREAD

**Issue by white-gthb** [AutoHotkey/AutoHotkeyUX#3]
It's not a major issue, but I mention it anyway.

In Windows, you can use multiple apps to open files of a specific file type. When you choose to `Open` a file, the default app will launch. If you choose `Open with` you can select which app you want to use.

In Dash you can change the script editor. The subtext says "Set your default script editor". But AutoHotkey can only use 1 editor to edit script files. There is no `Edit script with` function. Therefore, the term **default script editor** makes no sense. It's simply **the script editor**.

https://github.com/AutoHotkey/AutoHotkeyUX/blob/38aa5d7055a358aeb7d266d7782f54385983d49b/ui-dash.ahk#L45

Maybe change it to "Set the script editor"?

**Comment by Lexikos** [comment]
I currently have scripts open in SciTE4AutoHotkey and VS Code. I also have Notepad++ installed and configured with AutoHotkey syntax highlighting, and I have trialed various other editors. These are all script editors, and I have none of them set as "the" script editor.

> *default*: a preselected option adopted by a computer program or other mechanism when no alternative is specified by the user or programmer.

There are several ways to open a script for editing in a non-default script editor, including one you already mentioned: Open with. Other ways include passing the script path via command line, or opening the file from within the editor.

There is no "Edit script with" as part of a standard installation, but it could easily be implemented by a future version or by the user. I would not implement it because it would be redundant, given that it basically would be "Open with" minus any options that aren't editors. Furthermore, the Windows 11 context menu only shows specific verbs; it would show "Open with" by default but would not show "Edit script with" (unless we use a verb name that is hard-coded to be shown, like "pintohome").

**Comment by white-gthb** [comment]
I think your reasoning is flawed. But this is a minor issue, so I'll leave it at that.
